package command

// raffleLines head a raffle's winners, one picked at random each time.
// The message adds the colon.
var raffleLines = []string{
	"Lady Luck smiles on",
	"The dice have spoken",
	"Fortune favours",
	"Luck picked",
	"And the lucky ones are",
	"The stars aligned for",
	"Today's chosen ones",
	"Fate has decided",
	"The universe picked",
	"Drumroll, please",
	"Out of the hat come",
	"The wheel stopped on",
	"Destiny calls",
	"Pulled from the bowl",
	"The coin landed on",
	"Rolled a natural 20",
	"The algorithm has chosen",
	"Hand-picked by chance",
	"The lucky stars are",
	"Jackpot goes to",
	"Winner winner, chicken dinner",
	"The odds were ever in favour of",
	"Fortune's wheel points at",
	"Plucked from the crowd",
	"The prophecy names",
	"Cosmic lottery results",
	"Hold your applause for",
	"The magic 8-ball says",
	"Chosen by the RNG gods",
	"Shake the box, out come",
	"Today's four-leaf clovers",
	"The golden tickets go to",
	"Picked fair and square",
	"Lightning struck",
	"The raffle gods smile on",
	"Somebody's lucky day",
	"Spin, spin, spin… it's",
	"Straight out of the lucky jar",
	"The blindfolded pick is",
	"Tonight's headliners",
	"By sheer chance",
	"The ballots have been drawn",
	"A round of applause for",
	"The dice rolled in favour of",
	"Heads it is for",
	"Luck of the draw lands on",
	"Your lucky charms",
	"The numbers called",
	"Ding ding ding",
	"Mother Fortune chose",
	"Picked from a very fancy hat",
	"Random, but meant to be",
	"Freshly drawn",
	"The oracle points to",
	"Let's hear it for",
	"Today's lucky folks",
	"Big congrats to",
	"The cards revealed",
	"Hot off the shuffle",
	"Shuffled, cut and dealt to",
	"The hamster on the wheel chose",
	"The crystal ball shows",
	"Rolled snake eyes for everyone but",
	"Bingo",
	"Called by the dice",
	"Plot twist, it's",
	"The lucky dip brings up",
	"Selected by pure chaos",
	"No take-backs",
	"The claw machine grabbed",
	"Fished out of the pond",
	"The slot machine says",
	"Lucky number holders",
	"The stars point to",
	"Fortune cookie says",
	"Chance has chosen",
	"The draw is in",
	"Kismet",
	"Cue the confetti for",
	"Envelope, please",
	"The roulette ball landed on",
	"Fresh from the lottery drum",
	"The random number generator blesses",
	"Straight from the hat",
	"Luck's on the side of",
	"Lucky streak goes to",
	"Get your victory dance ready",
	"The dice don't lie",
	"Tossed, turned and picked",
	"Here come the chosen",
	"This round goes to",
	"Spotlight on",
	"Today the dice love",
	"Fortune knocked on the door of",
	"The jar has spoken",
	"Pure luck, no rigging",
	"Picked by the rolling dice",
	"Mic drop for",
	"Lucky ducks",
	"And the draw goes to",
}
